/*

 SIMPLEBACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\juan\Documents\GB_projects\4_backgrounds\simple_background\simple_background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

// #define simpleBackgroundMapWidth 40
// #define simpleBackgroundMapHeight 18
// #define simpleBackgroundMapBank 0

extern unsigned char windowMap[];

/* End of SIMPLEBACKGROUNDMAP.H */
